#!/usr/bin/python
import sys

import logging
from suds.client import Client

#app specific
import config
import utils

logging.basicConfig(level=logging.INFO, filename='jira.log', format='%(asctime)s %(levelname)s\n%(message)s\n\n')
client = Client(config.wsdl)
auth = client.service.login(config.username, config.password)

f = open(sys.argv[1], 'r')
comment = f.read()
f.close()

utils.verifyIssue(config, client, auth, comment, None, True)

exit(0)

# #do this only when the github hook calls us on a successful git push  
# for issueID in issueIDs:
#   print "adding comment for JIRA issue:", issueID
#   client.service.addComment(auth, issueID, {'body': comment})